# Generated by Django 6.1 on 2026-08-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pibfpgas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pi",
            options={"ordering": ["switch", "port"]},
        ),
        migrations.AddField(
            model_name="pi",
            name="fpga_board",
            field=models.CharField(
                blank=True,
                help_text='Attached FPGA board, e.g. "Digilent Arty A7-35T"',
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="pi",
            name="switch",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="VLAN-per-port switch number; empty = legacy flat scheme",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pi",
            name="serial_no",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
