# Generated by Django 6.1 on 2026-10-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pibfpgas", "0002_alter_pi_options_pi_fpga_board_pi_switch_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pi",
            name="fpga_board",
        ),
    ]
