# Generated by Django 6.1 on 2026-08-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("switch", models.PositiveSmallIntegerField(default=1)),
                (
                    "port",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="s3300 port; empty = not wired yet",
                        null=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("asic", "TT ASIC"),
                            ("kianv", "KianV RISC-V"),
                            ("fpga", "FPGA emulation"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "shuttle",
                    models.CharField(
                        blank=True,
                        help_text="e.g. tt06; blank for FPGA boards",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("blurb", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True, help_text="Markdown")),
                ("pcb", models.CharField(blank=True, max_length=80)),
                ("pmods", models.JSONField(blank=True, default=list)),
                ("links", models.JSONField(blank=True, default=list)),
                ("enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "slug"],
            },
        ),
    ]
