# Generated by Django 6.1 on 2026-08-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ttsite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="description",
            field=models.TextField(
                blank=True, help_text="Plain text; line breaks are kept"
            ),
        ),
    ]
