# Generated by Django 6.1 on 2026-09-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ttsite", "0002_alter_board_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="commander",
            field=models.CharField(
                choices=[
                    ("main", "Commander"),
                    ("legacy", "Legacy Commander (pre-2.x firmware)"),
                ],
                default="main",
                max_length=8,
            ),
        ),
    ]
