# Generated by Django 6.1 on 2026-08-31 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HardwareSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("document", models.JSONField()),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_confirmed", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["first_seen"],
            },
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial", models.CharField(max_length=32, unique=True)),
                ("site", models.CharField(max_length=32)),
                ("hostname", models.CharField(blank=True, max_length=64)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField()),
                ("online", models.BooleanField(default=False)),
                ("last_boot_id", models.CharField(blank=True, max_length=40)),
                ("last_uptime_s", models.PositiveIntegerField(default=0)),
                (
                    "latest_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="fleet.hardwaresnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["site", "hostname", "serial"],
            },
        ),
        migrations.AddField(
            model_name="hardwaresnapshot",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshots",
                to="fleet.machine",
            ),
        ),
        migrations.CreateModel(
            name="BootEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boot_id", models.CharField(max_length=40)),
                ("stage", models.CharField(max_length=64)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("ts", models.DateTimeField(db_index=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="fleet.machine",
                    ),
                ),
            ],
            options={
                "ordering": ["ts"],
            },
        ),
        migrations.AddConstraint(
            model_name="hardwaresnapshot",
            constraint=models.UniqueConstraint(
                fields=("machine", "fingerprint"), name="uniq_machine_fingerprint"
            ),
        ),
    ]
