# Generated by Django 6.1 on 2026-10-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['site', 'hostname', 'serial', 'verified_port']},
        ),
        migrations.AddField(
            model_name='machine',
            name='verified_port',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='machine',
            name='serial',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.UniqueConstraint(fields=('verified_port', 'serial'), name='uniq_machine_port_serial'),
        ),
    ]
