# Generated by Django 6.1 on 2026-10-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='verified_port',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
